services:
  postgres:
    container_name: postgres_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
    ports:
      - "${DATABASE_PORT_EXT}:${DATABASE_PORT_INT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_net
  django:
    build: .
    container_name: api_django
    command: /bin/bash -c "python manage.py makemigrations --noinput && python manage.py migrate && uvicorn --reload --log-level debug --host 0.0.0.0 --port 8000 --timeout-keep-alive 300 --workers ${WORKERS:-2} cartas.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media-volume:/app/media
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - main_net


networks:
  main_net:
    driver: bridge

volumes:
  postgres_data:
  media-volume:
